spring:
  application:
    name: employee-management-api

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: "bhanu#1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
  jackson:
    time-zone: Asia/Kolkata

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

application:
  security:
    jwt:
      secret-key: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb25UaGF0SXNMb25nRW5vdWdoMTIzNDU2
      expiration: 86400000

file:
  upload-dir: uploads